# Generated by Selenium IDE
# 导入所需的库
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By


# 定义测试类
class TestStartnet():
  # 设置方法，在每个测试方法之前执行
  def setup_method(self):
    # 初始化WebDriver
    self.driver = webdriver.Chrome()
    self.vars = {}

  # 拆卸方法，在每个测试方法之后执行
  def teardown_method(self):
    # 退出WebDriver
    self.driver.quit()

  # 定义测试方法
  def test_start_net(self):
    # 尝试执行测试步骤
    try:
    # Test name: start_net
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("http://10.2.5.251/")
        self.driver.set_window_size(1032, 995)
        # 使用JavaScript来执行点击操作，不受元素遮挡的影响
        element = self.driver.find_element(By.CSS_SELECTOR, ".edit_lobo_cell:nth-child(2)")
        self.driver.execute_script("arguments[0].scrollIntoView();", element)

        self.driver.find_element(By.CSS_SELECTOR, ".edit_lobo_cell:nth-child(2)").send_keys("TS22060150P31")

        self.driver.find_element(By.CSS_SELECTOR, ".edit_lobo_cell:nth-child(3)").send_keys("WDSRwdsr19990704")
        element2 = self.driver.find_element(By.NAME, "ISP_select")
        self.driver.execute_script("arguments[0].click();", element2)
        dropdown = self.driver.find_element(By.NAME, "ISP_select")
        dropdown.find_element(By.XPATH, "//option[. = '中国移动']").click()
        element3 = self.driver.find_element(By.CSS_SELECTOR, ".edit_lobo_cell:nth-child(1)")
        self.driver.execute_script("arguments[0].click();", element3)
        # print('network start')

    # 捕获并打印任何异常
    except Exception as e:
      print(f"测试过程中发生错误: {e}")

    # 测试完成后关闭浏览器
    finally:
      self.driver.close()
